spring:
  application:
    name: loveable
  datasource:
    url: jdbc:postgresql://localhost:9001/testDB?serverTimezone=Asia/Kolkata
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    connection:
        timezone: Asia/Kolkata
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

jwt:
  secret-key: ahduiahf7erfdjsoihf4y52jfashf0usd0f0dfnisa843nakbfi33nr9g8
##Should not be exposed to production environment